[package]
name = "player-profile"
version = "0.1.0"
description = "Player Profile Program for Dungeons & Moles"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "player_profile"

[features]
default = []
alloc = []
client = []
cpi = ["no-entrypoint"]
debug = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["quasar-lang/idl-build"]

[dependencies]
quasar-lang = { git = "https://github.com/blueshift-gg/quasar" }
solana-program-error = "3.0.0"
zeropod = "0.3.3"
