[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gameplay_state = "C8hK4qsqsSYQeqyXuTPTUUS3T7N74WnZCuzvChTpK1Mo"
map_generator = "GCy5GqvnJN99rgGtV6fMn8NtL9E7RoAyHDGzQv8me65j"
nft_marketplace = "ApUAEEKYsRMjxoMA65WV2xiG8xGwWzFhHjTMGGefcumK"
player_inventory = "APRnvp41jEYnT1EnrdBTim7bodqE6v2RSgzv1CG7Qv7u"
player_profile = "Ch3bbL1oQk2z5rX1jiun3KuSWZqnXZ1MnrfrtKj4MKun"
poi_system = "KiT25b86BSAF8yErcWwyuuWNaoXMpNf859NjH41TpSj"
session_manager = "6w1XVMSTRmZU9AWCKVvKohGAHSFMENhda7vqhKPQ8TPn"

[programs.localnet]
gameplay_state = "C8hK4qsqsSYQeqyXuTPTUUS3T7N74WnZCuzvChTpK1Mo"
map_generator = "GCy5GqvnJN99rgGtV6fMn8NtL9E7RoAyHDGzQv8me65j"
nft_marketplace = "ApUAEEKYsRMjxoMA65WV2xiG8xGwWzFhHjTMGGefcumK"
player_inventory = "APRnvp41jEYnT1EnrdBTim7bodqE6v2RSgzv1CG7Qv7u"
player_profile = "Ch3bbL1oQk2z5rX1jiun3KuSWZqnXZ1MnrfrtKj4MKun"
poi_system = "KiT25b86BSAF8yErcWwyuuWNaoXMpNf859NjH41TpSj"
session_manager = "6w1XVMSTRmZU9AWCKVvKohGAHSFMENhda7vqhKPQ8TPn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
e2e-gameplay = "yarn run ts-mocha -p ./tsconfig.json -t 300000 tests/e2e/track2-gameplay/**/*.ts --exit"
e2e-nft = "yarn run ts-mocha -p ./tsconfig.json -t 120000 tests/e2e/track1-nft/**/*.ts --exit"
init = "yarn run ts-node scripts/init.ts"
init-collections = "yarn run ts-node scripts/init-collections.ts"
mint-nft = "yarn run ts-node scripts/mint-nft.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --ignore 'tests/session-manager/manual-session-delegate-flow.ts' --ignore 'tests/e2e/**/*.ts' tests/**/*.ts"
