[package]
name = "nft-marketplace"
version = "0.1.0"
description = "NFT Marketplace and Quest System for Dungeons & Moles"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "nft_marketplace"

[features]
default = []
alloc = []
client = []
cpi = ["no-entrypoint"]
debug = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["quasar-lang/idl-build"]

[dependencies]
quasar-lang = { git = "https://github.com/blueshift-gg/quasar" }
solana-program-error = "3.0.0"
zeropod = "0.3.3"

[target.'cfg(not(any(target_os = "solana", target_arch = "bpf")))'.dependencies]
wincode = { version = "=0.4.9", features = ["derive"] }
